version: '3.5'

services:
  backend:
    build: backend/
    ports:
      - 8000:8000
    networks:
      - test_net
    container_name: backendcon

  frontend:
    build: frontend/
    depends_on:
      - backend
    ports:
      - 8501:8501
    networks:
      - test_net
    container_name: frontendcon

networks:
  test_net:
    driver: bridge
